//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forestitan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "*Required")]
        public string First_Name { get; set; }

        [Required(ErrorMessage = "*Required")]
        public string Last_Name { get; set; }
        [Required(ErrorMessage = "*Required")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "*Required")]
        [MinLength(10, ErrorMessage = "Phone Number should be at least 11 digit")]
        [MaxLength(12)]
        public string PhoneNo { get; set; }

        [Required(ErrorMessage = "*Required")]
        public string Course { get; set; }
    }
}
